export default {
  NAME_MAX_LENGTH: 64,
  EMAIL_MAX_LENGTH: 256,
  PASSWORD_MAX_LENGTH: 128,
  PASSWORD_HASH_SALT_LENGTH: 10,
  USERNAME_MIN_LENGTH: 4,
  USERNAME_MAX_LENGTH: 255,
  PASSWORD_MIN_LENGTH: 6,
};
